language: java
sudo: false
script: mvn clean package -Dmaven.test.skip=true
deploy:
   provider: cloudfoundry
   username: jhonatantiradotiradodeep@gmail.com
   password:
    secure: "yZLUX+4I5KsVpKGiO+t4NELjAwdfEsnrMbeJaCBYVzQFgSBaY51ueWhOjv+J+7CzQaoHT6zkeNBkELfazzOSOOTbMobuR1DKw7RxPG7la0X+8
uSpc77j+18hrOPflMZ8eK9thfGk+GgJb7zdtEfK2cm0UM07EN661q5fqA7KT8frTB4Y+HTtkqXzExGEY1kUjyfpKUF/fHVtFWZuumWqyphBicmO30TEos4LM
a8IhHasg0i+hJ9Vs+bfgs/l4sVmE9uEM85tYUwuCwxrIKmTXdLOl7ZZmBDtZ+rXd/ThWfLFSFhac2Aw8MRARnGDuT1MJ8g5X6vzsr6Ff4C8EvGS2VxyYyErg
2dLqdZZ4FLT17RKWak/HHKri7HfhnDKUmaPGSXBr3+1+wb/6eSkFuyO0+ifUWM/IzyztczSREHUmBXt1VA5BOV9zbFs9tSb1NI9giT8fXnZzZpOHDPOVPjg8
Ar2IiyJnnT7euf+xhaMA7mtPdksvruXE0IpiTht6aWZ7hbJhOPnrmN/cJEDIbG4OHbtA8ewcBlcSEtzL5MGlPIkFuU6Xa4IMPX1O1M5Z9pVoCwCQhtp5vtE8
aVX+/FRZgeAOY63t3TGg6gquBxKF1R1Ne/X5HBAHLV+zIF9ZU/4u5ca+jEnxdkGgn+WPEgyVIwctA1tL+mlQSVlaRLkDl8="
   api: https://api.run.pivotal.io
   organization: kipubit
   space: development